import lukeSkywalker from './Luke_skywalker.jpg';
import c3po from './C3POpromo.jpg';
import r2d2 from './R2-D2_Droid.png';
import darthVader from './Darth_Vader.png';
import leiaOrgana from "./Princess_Leia's_characteristic_hairstyle.jpg";
import owenLars from './OwenLars.webp';
import beruLars from './BeruCardTrader.webp';
import r5d4 from './R5-D4_Sideshow.webp';
import biggsDardlighter from './BiggsHS-ANH.webp';
import obiwanKenobi from './Obiwan1.jpg';

export const cardsData = [
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    url: 'https://swapi.dev/api/people/1/',
    image: lukeSkywalker,
  },
  {
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'n/a',
    skin_color: 'gold',
    eye_color: 'yellow',
    birth_year: '112BBY',
    gender: 'n/a',
    url: 'https://swapi.dev/api/people/2/',
    image: c3po,
  },
  {
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, blue',
    eye_color: 'red',
    birth_year: '33BBY',
    gender: 'n/a',
    url: 'https://swapi.dev/api/people/3/',
    image: r2d2,
  },
  {
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    birth_year: '41.9BBY',
    gender: 'male',
    url: 'https://swapi.dev/api/people/4/',
    image: darthVader,
  },
  {
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '19BBY',
    gender: 'female',
    url: 'https://swapi.dev/api/people/5/',
    image: leiaOrgana,
  },
  {
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hair_color: 'brown, grey',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '52BBY',
    gender: 'male',
    url: 'https://swapi.dev/api/people/6/',
    image: owenLars,
  },
  {
    name: 'Beru Whitesun lars',
    height: '165',
    mass: '75',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'blue',
    birth_year: '47BBY',
    gender: 'female',
    url: 'https://swapi.dev/api/people/7/',
    image: beruLars,
  },
  {
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, red',
    eye_color: 'red',
    birth_year: 'unknown',
    gender: 'n/a',
    url: 'https://swapi.dev/api/people/8/',
    image: r5d4,
  },
  {
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    birth_year: '24BBY',
    gender: 'male',
    url: 'https://swapi.dev/api/people/9/',
    image: biggsDardlighter,
  },
  {
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'auburn, white',
    skin_color: 'fair',
    eye_color: 'blue-gray',
    birth_year: '57BBY',
    gender: 'male',
    url: 'https://swapi.dev/api/people/10/',
    image: obiwanKenobi,
  },
];
